### ISSUE TITLE
essex_hog flexibility enhancement

### ISSUE THREAD

**Issue by cmiller123456** [newrelic/rusty-hog#26]
Hi. Attempting to use essex_hog, but the resulting URL does not align with the behind-the-firewall Confluence site I'm attempting to scan due to it's inclusion of /wiki/ in the URL.

Example: 
essex_hog attempts to retrieve: https://confluence.example.domain/wiki/rest/api/content/39273027?expand=body.storage

while the correct URL to body.storage would be: https://confluence.example.domain/rest/api/content/39273027?expand=body.storage

Thank-you.

**Comment by cutler-scott-newrelic** [comment]
Interesting, thanks for the submission, I'll take a look when I can but I'm
leaving on vacation shortly so it may be a couple weeks.

**Comment by cmiller123456** [comment]
Okay, thank-you Scott! We anxious to give this a whirl. :)

**Comment by bp4151** [comment]
I know this issue is ancient, but it's something we need so I coded it and there is a PR waiting. It turns out the Confluence context is hard-coded. If that's removed, then it will work just fine for anyone not using context, and for those who are, simply appending the context to the base URL should be fine.

**Comment by cutler-scott-newrelic** [comment]
Awesome, thank you, yeah I didn't have the resources to investigate this so
I very much appreciate it. I'll test and merge the PR today.

**Comment by cutler-scott-newrelic** [comment]
I believe this was fixed with https://github.com/newrelic/rusty-hog/commit/5078d72c869e2bd6960a5b7cf35021aa659d2d07 so I will close this. Let me know if it's still an issue.

**Comment by cmiller123456** [comment]
Not sure why this still doesn't work for me.

docker run -it --rm wetfeet2000/essex_hog:1.0.8 --username '***********'
--password '*************' ###### https://wiki.domain.com
docker run -it --rm wetfeet2000/essex_hog:1.0.8 --username '***********'
--password '*************' ###### https://wiki.domain.com/

both produce:

thread 'main' panicked at 'Request to
https://wiki.domain.com/wiki/rest/api/content/######?expand=body.storage
failed with code 404 Not Found: (as the /wiki/ reference is still there.)

**Comment by cutler-scott-newrelic** [comment]
Hey cmiller, the update is only in the master branch at the moment, I'm hoping to post a new release with a batch of fixes early next week. I can test this on my end later today, but can you confirm the error you're seeing is from the binary you compiled based the latest master branch commit ?

**Comment by cutler-scott-newrelic** [comment]
So I tested this on the latest commit in master and it works, you can see that on my end I have to include the /wiki in the URL, otherwise it dosen't include it by default. I'll keep this issue open until I post a formal release with this fix or you respond once you're able to test on your end.

To test this on your end, you'll want to do the following...

1. Clone the New Relic repo with `git clone https://github.com/newrelic/rusty-hog.git`
2. CD into the repository `cd rusty-hog`
3. Compile it with Rust using `cargo build --release`
4. Test the newly compiled binary with `target/release/essex_hog ...`
 
![Screen Shot 2021-04-15 at 11 02 03 AM](https://user-images.githubusercontent.com/47458753/114917022-5803af80-9dda-11eb-9dab-c8692e57a95b.jpg)
![Screen Shot 2021-04-15 at 11 01 41 AM](https://user-images.githubusercontent.com/47458753/114917029-5934dc80-9dda-11eb-9b42-d35b409a0bf9.jpg)

**Comment by cmiller123456** [comment]
Got it now - thank you so much Scott. Working perfectly now!

**Comment by cutler-scott-newrelic** [comment]
@cmiller123456 awesome! I'm working on bug fixes, feature requests, etc. all this week and then I'll compile everything into a single release (v1.0.9) some time next week.
