### ISSUE TITLE
Choctaw_hog: Enable parallel processing

### ISSUE THREAD

**Issue by madchap** [newrelic/rusty-hog#46]
## Summary

The current implementation only uses a single CPU core.

## Desired Behaviour

It would be great to leverage all compute power (or provide an option of number of core to use) to hunt down secrets.

## Additional context

When scanning entire repositories, the scan can take a long time to complete -- too long in some cases.

**Comment by cutler-scott-newrelic** [comment]
So there are a few big issues around this, but the big one is that Rusty Hog relies on the git2 rust crate (https://docs.rs/git2/latest/git2/) which hasn't implemented any Rust-native async features or thread-safety. In addition, the library is mainly a wrapper around a C library and I have no clue about how thread safety works in this scenario. When I first started writing Rusty Hog there was no alternative, but it appears there is a new Rust-native Git implementation here: https://github.com/Byron/gitoxide , and it's likely this would support async and threads features from Rust that we could leverage. If someone wants to rewrite the GitScanner engine I'm all for merging a PR, but I'm not sure I have the time to re-write that much of the Git code. (Though I'm happy to tinker around if I do have time) I'll keep this issue request open for when the security automation tools team at New Relic takes ownership next year. 

A couple other thoughts: 

1) This tool was originally created to do Git scanning at a much bigger scale, we currently use it to scan 500+ repos daily at New Relic. In that case, the single-threaded nature works nicely because we simply scale horizontally and scan multiple repos simultaneously using a Python pool (https://github.com/newrelic/rusty-hog/blob/master/scripts/ghe_secret_monitor.py#L136). Doing this we saturate 16 core VMs without much effort. 

2) I'd be curious about just how bad the single threaded performance is for you, and the specifics about how you're using the tool to say it's too long. If you have a link to a public repo and the exact syntax you're using I can compare it on my machine. Out of curiosity I ran `time` against our biggest internal repo with 90k commits and the default choctaw_hog settings on my M1 laptop and got this: `1084.81s user 36.33s system 97% cpu 19:07.73 total`, so about 19 minutes to run. That isn't great, but it also feels reasonable considering the default settings of running 50+ regular expressions, three of which include entropy calculations. If you're really concerned about speed I'd offer a couple of suggestions: make sure you're using `--release` in your cargo build command to add all the rust optimizations, tune your regex file, if you're monitoring the same repo over time use `--recent_days` or `--since_commit` to limit your scan to commits you haven't already scanned.

**Comment by madchap** [comment]
Hi @cutler-scott-newrelic 

Thanks for taking the time to answer thoroughly :)

Unfortunately no link to a public repo. The scan was also taking in all of history and there was a lot. I ran it on the last 30 days, much better of course. The initial scan can take longer, I won't actually care that much (I think). I'll have many thousands repo to scan eventually, but as you pointed out, I'll scale horizontally.

Please disregard this request and thanks again.
